services:
  php:
    http: false
    image: tugboatqa/php:8.1-apache-bullseye
    default: true

    depends:
      - mysql
      - memcached

    commands:
      init: ./.tugboat/steps/init.sh
      update: ./.tugboat/steps/update.sh
      build: ./.tugboat/steps/build.sh

  mysql:
    image: tugboatqa/mysql:5.7
    commands:
      update:
        - echo "Nothing to do as we import databases from the Drupal service."

  memcached:
    image: tugboatqa/memcached:1
